### ISSUE TITLE
POST event layer returns "entity too large"

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/ADA-API#20]
**Describe the bug**
Getting error 413 'request entity too large' when POST [this file](https://www.geoboundaries.org/data/geoBoundaries-3_0_0/AFG/ADM1/geoBoundaries-3_0_0-AFG-ADM1.geojson) (2.8 MB) as admin-1 layer.

**To Reproduce**
Example python code:
```
# post event layer
layer = "admin-1"
url = "https://www.geoboundaries.org/data/geoBoundaries-3_0_0/AFG/ADM1/geoBoundaries-3_0_0-AFG-ADM1.geojson"
data = str(requests.get(url).json())
print(sys.getsizeof(data))
res = requests.post(f'http://20.234.160.246/events/{id}/layers/{layer}', headers=headers, data=data)
print(res)
```

**Expected behaviour**
No error

**Comment by gulfaraz** [comment]
This is resolved in #24
